name: CI - Build, Test and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Build and analyze
        run: |
          dotnet-sonarscanner begin /k:"perasd9_PTP-CS-DBEngine" /o:"perasd9" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"


      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DCK_USR }}
          password: ${{ secrets.DCK_PASS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DCK_USR }}/ptp:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DCK_USR }}/ptp:latest
